# Generated by Django 5.0.3 on 2024-04-17 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_glist_delete_grocery_list_alter_grocery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
