# Generated by Django 5.0.3 on 2024-04-17 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0002_grocery_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='GList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('date_of_creation', models.DateTimeField()),
                ('groceries', models.ManyToManyField(to='groceries.grocery')),
            ],
        ),
        migrations.DeleteModel(
            name='grocery_list',
        ),
    ]
